---
title: "My title"
author: "Inessa De Angelis"
thanks: "Code and data from this analysis are available at: https://github.com/InessaDeAngelis/Perceptions_of_Women_in_Politics "
date: "today"
date-format: "long"
abstract: "First sentence. Second sentence. Third sentence. Fourth sentence."
format: pdf
toc: true
number-sections: true
bibliography: references.bib
---

```{r}
#| include: false
#| warning: false
#| message: false

#### Workspace set-up ####

## Load packages ##

library(tidyverse)
library(knitr)
library(kableExtra)
library(here)
library(ggplot2)
library(ggbeeswarm)
library(ggrepel)

# Read in cleaned respondent info data #
cleaned_respondent_info <- read.csv(here::here("outputs/data/cleaned_respondent_info.csv"))
show_col_types = FALSE

# Read in cleaned women in politics data #
cleaned_women_in_politics <- read.csv(here::here("outputs/data/cleaned_women_in_politics.csv"))
show_col_types = FALSE

# Read in summarized voter statistics data #
summarized_political_preferences <- read.csv(here::here("outputs/data/summarized_political_preferences.csv"))
show_col_types = FALSE
```

## Introduction 



## Data


### Respondent Demographic Information

```{r}
#| message: false
#| echo: false
#| label: tbl-cleaned_respondent_info
#| tbl-cap: Sample of Cleaned Respondent Demographic Information

head (cleaned_respondent_info, 10) |>
  kable(
    col.names = c("Year", "ID", "Age",	"Gender"),
  booktabs = TRUE
  )
```

### Perceptions of Women in Politics


### Political Preferences


## Results


## Discussion


## Conclusion


## Appendix {.unnumbered}


## References
